# Generated by Django 3.0.7 on 2020-07-31 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('memberNo', models.IntegerField(auto_created=True, default=0, primary_key=True, serialize=False)),
                ('memberName', models.CharField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('projectNo', models.IntegerField(auto_created=True, default=0, primary_key=True, serialize=False)),
                ('projectName', models.CharField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1023)),
                ('date', models.DateTimeField(auto_now=True)),
                ('media', models.FileField(blank=True, upload_to='media')),
                ('brach', models.IntegerField(default=0)),
                ('memberNo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Members')),
                ('previous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Posts')),
                ('projectNo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Projects')),
            ],
        ),
    ]
