# Generated by Django 2.2.3 on 2020-06-23 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_post_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewEntry',
            fields=[
                ('series', models.IntegerField(default=0, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.NewEntry'),
        ),
    ]
