# Generated by Django 2.2.3 on 2020-06-23 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200624_0204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='series',
        ),
    ]
