# Generated by Django 2.2.3 on 2020-06-23 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_post_series'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewEntry',
        ),
    ]
