# Generated by Django 3.0.7 on 2020-07-17 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_node'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Node',
        ),
    ]
